Repository SeedCompany/cord-api-v3, pull requests merged in 2020-10, with the labels that each got.

#1211 Update partnership to have partner relation
  src/components/authorization/policies/policies.ts
  src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts
  src/components/partnership/dto/create-partnership.dto.ts
  src/components/partnership/dto/partnership.dto.ts
  src/components/partnership/partnership.module.ts
  src/components/partnership/partnership.resolver.ts
  src/components/partnership/partnership.service.spec.ts
  src/components/partnership/partnership.service.ts
  src/components/project/project.module.ts
  src/components/project/project.service.ts
  test/partnership.e2e-spec.ts
  test/project.e2e-spec.ts
  test/utility/create-partnership.ts
  test/utility/fragments.ts
Labels: Don't merge

#1222 Add types to partner module
  src/components/authorization/policies/policies.ts
  src/components/budget/handlers/sync-budget-records-to-funding-partners.handler.ts
  src/components/partner/dto/create-partner.dto.ts
  src/components/partner/dto/index.ts
  src/components/partner/dto/list-partner.dto.ts
  src/components/partner/dto/partner-type.enum.ts
  src/components/partner/dto/partner.dto.ts
  src/components/partner/dto/update-partner.dto.ts
  src/components/partner/partner.service.ts
  src/components/partnership/dto/create-partnership.dto.ts
  src/components/partnership/dto/index.ts
  src/components/partnership/dto/partnership-type.enum.ts
  src/components/partnership/dto/partnership.dto.ts
  src/components/partnership/dto/update-partnership.dto.ts
  src/components/partnership/partnership.service.spec.ts
  src/components/partnership/partnership.service.ts
  src/components/project/project.service.ts
  test/budget.e2e-spec.ts
  test/partner.e2e-spec.ts
  test/partnership.e2e-spec.ts
  test/project.e2e-spec.ts
  test/utility/create-partner.ts
  test/utility/create-partnership.ts
  test/utility/fragments.ts
Labels: breaking change

#1340 254 project workflow
  src/common/secured-property.ts
  src/components/admin/admin.service.ts
  src/components/authentication/authentication.service.ts
  src/components/authorization/authorization.resolver.ts
  src/components/authorization/authorization.service.ts
  src/components/project/dto/status.enum.ts
  src/components/project/dto/step.enum.ts
  src/components/project/handlers/index.ts
  src/components/project/handlers/step-changed-notification.handler.ts
  src/components/project/index.ts
  src/components/project/project-step.resolver.ts
  src/components/project/project.module.ts
  src/components/project/project.resolver.ts
  src/components/project/project.rules.ts
  src/components/project/project.service.ts
  src/components/user/dto/create-person.dto.ts
  src/components/user/user.resolver.ts
  src/components/user/user.service.ts
  src/core/config/config.service.ts
  src/core/database/query.helpers.ts
  src/core/email/email.service.ts
  src/core/email/index.ts
  src/core/email/templates/base.tsx
  src/core/email/templates/forgot-password.template.tsx
  src/core/email/templates/forgot-password.tsx
  src/core/email/templates/frontend-url.tsx
  src/core/email/templates/index.ts
  src/core/email/templates/project-step-changed.template.tsx
  test/engagement.e2e-spec.ts
  test/project.e2e-spec.ts
  test/user.e2e-spec.ts
  test/utility/create-app.ts
  test/utility/create-graphql-client.ts
  test/utility/create-project.ts
  test/utility/grant-power.ts
  test/utility/login.ts
  test/utility/register.ts
  test/utility/transition-project.ts
  test/workflow.e2e-spec.ts
Labels: Don't merge, breaking change

#1056 add test case in budget
  test/budget.e2e-spec.ts
Labels: tests
