Repository SeedCompany/cord-api-v3, pull requests merged in 2020-09, with the labels that each got.

#1084 1071 add producible test
  test/film.e2e-spec.ts
  test/literacy.e2e-spec.ts
  test/song.e2e-spec.ts
  test/story.e2e-spec.ts
Labels: tests

#1070 Handle no permission for project root directory
  src/components/file/dto/node.ts
  src/components/project/project.resolver.ts
  src/components/project/project.service.ts
Labels: Don't merge, breaking change

#1076 fix:list view of project members by projectId test
  test/project.e2e-spec.ts
Labels: tests

#1088 add test into organization
  test/organization.e2e-spec.ts
Labels: tests

#1235 1229 active refactor
  src/common/session.ts
  src/components/admin/admin.service.ts
  src/components/authentication/authentication.service.ts
  src/components/authorization/authorization.service.ts
  src/components/budget/budget.service.ts
  src/components/ceremony/ceremony.service.ts
  src/components/ceremony/handlers/create-engagement-default-ceremony.handler.ts
  src/components/ceremony/handlers/delete-engagement-default-ceremony.handler.ts
  src/components/engagement/engagement.service.ts
  src/components/favorites/favorite.service.ts
  src/components/file/file.repository.ts
  src/components/file/handlers/attach-project-root-directory.handler.ts
  src/components/film/film.service.ts
  src/components/language/ethnologue-language/ethnologue-language.service.ts
  src/components/language/language.service.ts
  src/components/literacy-material/literacy-material.service.ts
  src/components/location/location.service.ts
  src/components/organization/organization.service.ts
  src/components/partner/partner.service.ts
  src/components/partnership/partnership.service.ts
  src/components/product/product.service.ts
  src/components/project/project-member/project-member.service.ts
  src/components/project/project.service.ts
  src/components/scripture/scripture-reference.service.ts
  src/components/search/search.service.ts
  src/components/song/song.service.ts
  src/components/story/story.service.ts
  src/components/user/education/education.service.ts
  src/components/user/unavailability/unavailability.service.ts
  src/components/user/user.service.ts
  src/components/workflow/workflow.service.ts
  src/core/database/database.service.ts
  src/core/database/query.helpers.ts
  src/core/database/query/matching.ts
  test/budget.e2e-spec.ts
  test/country.e2e-spec.ts
  test/education.e2e-spec.ts
  test/engagement.e2e-spec.ts
  test/favorite.e2e-spec.ts
  test/file.e2e-spec.ts
  test/film.e2e-spec.ts
  test/language.e2e-spec.ts
  test/literacy.e2e-spec.ts
  test/organization.e2e-spec.ts
  test/partnership.e2e-spec.ts
  test/product.e2e-spec.ts
  test/project-member.e2e-spec.ts
  test/project.e2e-spec.ts
  test/region.e2e-spec.ts
  test/song.e2e-spec.ts
  test/story.e2e-spec.ts
  test/unavailability.e2e-spec.ts
  test/user.e2e-spec.ts
  test/zone.e2e-spec.ts
Labels: DB SCHEMA CHANGE, Don't merge

#1251 E2E tests - Unchecked errors
  test/budget.e2e-spec.ts
  test/engagement.e2e-spec.ts
  test/language.e2e-spec.ts
  test/organization.e2e-spec.ts
  test/partnership.e2e-spec.ts
  test/project-member.e2e-spec.ts
  test/project.e2e-spec.ts
Labels: tests
